CREATE TABLE CUSTOMER (
customer_id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(200),
last_name VARCHAR(200),
phone_num VARCHAR(15) NOT NULL UNIQUE,
email VARCHAR(50) UNIQUE,
address VARCHAR(200),
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ADMIN(
admin_id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(200) NOT NULL,
last_name VARCHAR(200) NOT NULL,
phone_num VARCHAR(15) NOT NULL UNIQUE,
email VARCHAR(50) UNIQUE,
password VARCHAR(255) NOT NULL
);

CREATE TABLE CUSTOMER_ORDER(
order_id INT AUTO_INCREMENT PRIMARY KEY,
customer_id INT NOT NULL,
order_status VARCHAR(50) NOT NULL,
total DECIMAL(10,2) NOT NULL,
FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id)  ,
admin_id INT,
FOREIGN KEY(admin_id) REFERENCES ADMIN(admin_id)
);

CREATE TABLE PRODUCT(
product_id VARCHAR(15) NOT NULL PRIMARY KEY,
product_description TEXT NOT NULL,
image BLOB
);

CREATE TABLE ORDER_ITEM(
order_item_id INT AUTO_INCREMENT PRIMARY KEY,
price DECIMAL(10,2) NOT NULL,
quantity INT NOT NULL,
order_id INT NOT NULL,
FOREIGN KEY(order_id) REFERENCES CUSTOMER_ORDER(order_id),
product_id VARCHAR(15) NOT NULL,
FOREIGN KEY(product_id) REFERENCES PRODUCT(product_id)
);

CREATE TABLE REVIEW(
review_id INT AUTO_INCREMENT PRIMARY KEY,
review_description TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
customer_id INT NOT NULL,
FOREIGN KEY(customer_id) REFERENCES CUSTOMER(customer_id),
product_id VARCHAR(15) NOT NULL,
FOREIGN KEY(product_id) REFERENCES PRODUCT(product_id)
);

CREATE TABLE REFUNDS(
refund_id INT AUTO_INCREMENT PRIMARY KEY,
amount DECIMAL(10,2) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
admin_id INT NOT NULL,
FOREIGN KEY(admin_id) REFERENCES ADMIN(admin_id)
);

CREATE TABLE REFUND_ITEM(
refund_item_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
price DECIMAL(10,2) NOT NULL,
quantity INT NOT NULL,
customer_id INT NOT NULL,
FOREIGN KEY(customer_id) REFERENCES CUSTOMER(customer_id),
order_item_id INT NOT NULL,
FOREIGN KEY(order_item_id) REFERENCES ORDER_ITEM(order_item_id),
product_id VARCHAR(15) NOT NULL,
FOREIGN KEY(product_id) REFERENCES PRODUCT(product_id)
);

CREATE TABLE CART(
cart_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
total DECIMAL(10,2) NOT NULL,
customer_id INT NOT NULL,
FOREIGN KEY(customer_id) REFERENCES CUSTOMER(customer_id)
);

CREATE TABLE CART_ITEM(
cart_item_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
price DECIMAL(10,2) NOT NULL,
quantity INT NOT NULL,
cart_id INT NOT NULL,
FOREIGN KEY(cart_id) REFERENCES CART(cart_id),
product_id VARCHAR(15) NOT NULL,
FOREIGN KEY(product_id) REFERENCES PRODUCT(product_id)
);

CREATE TABLE ANALYTICS(
analytics_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
total_sales DECIMAL(10,2) NOT NULL,
quantity_sold INT NOT NULL,
most_sales DATE NOT NULL,
last_sold DATE NOT NULL,
avg_sales DECIMAL(10,2) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
product_id VARCHAR(15) NOT NULL,
FOREIGN KEY(product_id) REFERENCES PRODUCT(product_id)
);

